BrickView: Real Estate Analytics Platform

In [1]:
import json 
import pandas as pd

In [2]:
pip install matplotlib

Requirement already satisfied: matplotlib in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (3.10.9)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.23 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (2.4.1)
Requirement already satisfied: packaging>=20.0 in c:\users\user\appdata\roaming\python\python314\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\appdata\roaming\python\python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
pip install plotly

Collecting plotly
  Downloading plotly-6.7.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from plotly) (2.19.0)
Requirement already satisfied: packaging in c:\users\user\appdata\roaming\python\python314\site-packages (from plotly) (25.0)
Downloading plotly-6.7.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 5.0 MB/s eta 0:00:02
   ---- ----------------------------------- 1.0/9.9 MB 3.7 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/9.9 MB 2.8 MB/s eta 0:00:03
   -------- ------------------------------- 2.1/9.9 MB 2.6 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/9.9 MB 2.6 MB/s eta 0:00:03
   ---------- ----------------------------- 2.6/9.9 MB 2.4 MB/s eta 0:00:03
   ----------- ---------------------------- 2.9/9.9 MB 2.2 MB/s eta 0:00:04
   ------------ --------------------------- 3.1/9.9 MB 1.9 MB/s eta 0:00:04
   ------------ --------------------------- 3.1/9.9 MB 1.9 MB/s eta 0:00:04
   ------------- -------------------------- 3.4/9.9 MB 1.8 MB/s eta 0:00:04
   -------------- ------------------------- 3.7/9.9 MB 1.7 MB/s eta 0:00:04
   --------------- ------------------------ 3.9/9.9 MB 1.6 MB/s eta 0:00:04
   ---------------- ----------------------- 4.2/9.9 MB 1.6 MB/s eta 0:00:04
   ------------------ --------------------- 4.5/9.9 MB 1.5 MB/s eta 0:00:04
   ------------------- -------------------- 4.7/9.9 MB 1.5 MB/s eta 0:00:04
   ------------------- -------------------- 4.7/9.9 MB 1.5 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.9 MB 1.4 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.9 MB 1.4 MB/s eta 0:00:04
   --------------------- ------------------ 5.2/9.9 MB 1.4 MB/s eta 0:00:04
   ---------------------- ----------------- 5.5/9.9 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.9 MB 1.3 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.9 MB 1.3 MB/s eta 0:00:04
   ------------------------ --------------- 6.0/9.9 MB 1.3 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/9.9 MB 1.3 MB/s eta 0:00:03
   -------------------------- ------------- 6.6/9.9 MB 1.3 MB/s eta 0:00:03
   --------------------------- ------------ 6.8/9.9 MB 1.3 MB/s eta 0:00:03
   ---------------------------- ----------- 7.1/9.9 MB 1.3 MB/s eta 0:00:03
   ---------------------------- ----------- 7.1/9.9 MB 1.3 MB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 1.2 MB/s eta 0:00:03
   ------------------------------ --------- 7.6/9.9 MB 1.2 MB/s eta 0:00:02
   ------------------------------- -------- 7.9/9.9 MB 1.2 MB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 1.2 MB/s eta 0:00:02
   --------------------------------- ------ 8.4/9.9 MB 1.2 MB/s eta 0:00:02
   ---------------------------------- ----- 8.7/9.9 MB 1.2 MB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.9 MB 1.2 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 1.2 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 1.2 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 1.2 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 1.2 MB/s  0:00:08
Installing collected packages: plotly
Successfully installed plotly-6.7.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
listings_df = pd.read_json("listings_final_expanded.json")
property_df = pd.read_json("property_attributes_final_expanded.json")
agents_df = pd.read_json("agents_cleaned.json")
agents_enhanced_df = pd.read_json("agents_cleaned.json")
sales_df = pd.read_csv("sales_cleaned.csv")
buyers_df = pd.read_json("buyers_cleaned.json")

In [ ]:
#pip install mysql-connector-python sqlalchemy pymysql psycopg2

Requirement already satisfied: mysql-connector-python in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (9.6.0)
Requirement already satisfied: sqlalchemy in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (2.0.49)
Requirement already satisfied: pymysql in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (1.1.2)
Requirement already satisfied: psycopg2 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
listings_df.head(10)

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1.655144e+06,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1.519141e+06,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,1.624890e+05,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1.277016e+06,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,5.622970e+05,4178.997421,2023-10-29,A0018,39.425252,-83.917878
5,L00006,New York,House,1.564104e+06,3961.992616,2023-06-24,A0018,25.487793,-68.757114
6,L00007,Los Angeles,House,1.701163e+06,3257.015062,2023-02-22,A0006,44.969112,-112.678494
7,L00008,Houston,Apartment,8.528340e+05,3316.993721,2023-11-06,A0017,29.354913,-114.364681
8,L00009,New York,Townhouse,1.224551e+06,1522.007780,2024-05-13,A0025,32.302569,-94.556982
9,L00010,New York,Condo,1.839387e+06,3462.022639,2023-10-23,A0013,35.370397,-108.119318

In [5]:
x = 1e3
print(float(x))

1000.0

In [6]:
x = 5e2
print(float(x))

500.0

In [7]:
x = 5e2
print(int(x))

500

In [8]:
x = 1.655144e+06 
print(float(x))

1655144.0

In [9]:
listings_df['Price'] = listings_df['Price'].astype(int)

In [10]:
listings_df.head(10)

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1655144,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1519141,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,162488,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1277015,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,562297,4178.997421,2023-10-29,A0018,39.425252,-83.917878
5,L00006,New York,House,1564104,3961.992616,2023-06-24,A0018,25.487793,-68.757114
6,L00007,Los Angeles,House,1701163,3257.015062,2023-02-22,A0006,44.969112,-112.678494
7,L00008,Houston,Apartment,852834,3316.993721,2023-11-06,A0017,29.354913,-114.364681
8,L00009,New York,Townhouse,1224550,1522.007780,2024-05-13,A0025,32.302569,-94.556982
9,L00010,New York,Condo,1839386,3462.022639,2023-10-23,A0013,35.370397,-108.119318

In [11]:
listings_df.shape

(21200, 9)

In [12]:
listings_df["Date_Listed"].dtype

dtype('O')

In [13]:
listings_df["Date_Listed"]= pd.to_datetime(listings_df["Date_Listed"])

In [14]:
listings_df.head(5)

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1655144,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1519141,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,162488,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1277015,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,562297,4178.997421,2023-10-29,A0018,39.425252,-83.917878

In [15]:
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Listing_ID     21200 non-null  object
 1   City           21200 non-null  object
 2   Property_Type  21200 non-null  object
 3   Price          21200 non-null  int64
 4   Sqft           21200 non-null  float64
 5   Date_Listed    21200 non-null  datetime64[ns]
 6   Agent_ID       21200 non-null  object
 7   Latitude       21200 non-null  float64
 8   Longitude      21200 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 1.5+ MB

In [16]:
listings_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Listing_ID     21200 non-null  object
 1   City           21200 non-null  object
 2   Property_Type  21200 non-null  object
 3   Price          21200 non-null  int64
 4   Sqft           21200 non-null  float64
 5   Date_Listed    21200 non-null  datetime64[ns]
 6   Agent_ID       21200 non-null  object
 7   Latitude       21200 non-null  float64
 8   Longitude      21200 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(4)
memory usage: 1.5+ MB

In [17]:
listings_df = listings_df.drop_duplicates()

In [18]:
listings_df.isnull().sum()

Listing_ID       0
City             0
Property_Type    0
Price            0
Sqft             0
Date_Listed      0
Agent_ID         0
Latitude         0
Longitude        0
dtype: int64

In [19]:
listings_df.isnull()

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
21195,False,False,False,False,False,False,False,False,False
21196,False,False,False,False,False,False,False,False,False
21197,False,False,False,False,False,False,False,False,False
21198,False,False,False,False,False,False,False,False,False
21199,False,False,False,False,False,False,False,False,False

In [20]:
listings_df.dropna()

,Listing_ID,City,Property_Type,Price,Sqft,Date_Listed,Agent_ID,Latitude,Longitude
0,L00001,New York,Apartment,1655144,2753.009121,2023-05-06,A0015,33.965208,-69.861589
1,L00002,Los Angeles,Apartment,1519141,4966.988193,2023-02-14,A0038,42.547892,-90.277860
2,L00003,Houston,Apartment,162488,1267.003959,2023-04-22,A0015,28.732327,-115.952982
3,L00004,Phoenix,Apartment,1277015,2128.014429,2024-01-02,A0042,26.403938,-74.771490
4,L00005,Phoenix,Townhouse,562297,4178.997421,2023-10-29,A0018,39.425252,-83.917878
...,...,...,...,...,...,...,...,...,...
21195,L21196,Phoenix,House,709355,898.410000,2023-12-31,A0021,25.456929,-88.189857
21196,L21197,Phoenix,Condo,3288420,4195.680000,2023-07-23,A0005,40.926232,-80.167341
21197,L21198,Los Angeles,Apartment,1667441,8723.370000,2024-06-30,A0003,46.083306,-115.396164
21198,L21199,Los Angeles,Townhouse,1648411,8412.710000,2023-09-17,A0018,33.757737,-103.472564
21199,L21200,New York,Apartment,4991528,3994.920000,2023-07-28,A0008,42.222541,-119.219408

In [21]:
listings_df.columns = listings_df.columns.str.lower()

In [22]:
listings_df.columns

Index(['listing_id', 'city', 'property_type', 'price', 'sqft', 'date_listed',
       'agent_id', 'latitude', 'longitude'],
      dtype='object')

In [23]:
#listings_df.to_csv("listings_cleaned.csv", index=False)

In [24]:
agents_df.head()

,Agent_ID,Name,Phone,Email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,A0001,Agent A0001,+1-534-665-8373,a0001@realestate.com,2.00,52,4.3,10,64
1,A0002,Agent A0002,+1-493-463-4698,a0002@realestate.com,2.20,26,3.8,20,82
2,A0003,Agent A0003,+1-290-534-1121,a0003@realestate.com,2.85,297,3.6,21,83
3,A0004,Agent A0004,+1-691-610-4878,a0004@realestate.com,1.67,31,4.5,5,61
4,A0005,Agent A0005,+1-829-613-5411,a0005@realestate.com,1.11,198,4.3,16,67

In [25]:
agents_df.shape

(50, 9)

In [26]:
agents_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Agent_ID          50 non-null     object
 1   Name              50 non-null     object
 2   Phone             50 non-null     object
 3   Email             50 non-null     object
 4   commission_rate   50 non-null     float64
 5   deals_closed      50 non-null     int64
 6   rating            50 non-null     float64
 7   experience_years  50 non-null     int64
 8   avg_closing_days  50 non-null     int64
dtypes: float64(2), int64(3), object(4)
memory usage: 3.6+ KB

In [27]:
agents_df.columns = agents_df.columns.str.lower()

In [28]:
agents_df.columns

Index(['agent_id', 'name', 'phone', 'email', 'commission_rate', 'deals_closed',
       'rating', 'experience_years', 'avg_closing_days'],
      dtype='object')

In [29]:
agents_df = agents_df.drop_duplicates()

In [30]:
agents_df.isnull().sum()

agent_id            0
name                0
phone               0
email               0
commission_rate     0
deals_closed        0
rating              0
experience_years    0
avg_closing_days    0
dtype: int64

In [31]:
agents_df.isnull()

,agent_id,name,phone,email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False

In [32]:
agents_df['phone'] = agents_df['phone'].str.replace(r'\D', '', regex=True)
agents_df['phone'] = '+' + agents_df['phone']

In [33]:
agents_df['commission_rate'] = agents_df['commission_rate'].astype(float)

In [34]:
agents_df.head()

,agent_id,name,phone,email,commission_rate,deals_closed,rating,experience_years,avg_closing_days
0,A0001,Agent A0001,+15346658373,a0001@realestate.com,2.00,52,4.3,10,64
1,A0002,Agent A0002,+14934634698,a0002@realestate.com,2.20,26,3.8,20,82
2,A0003,Agent A0003,+12905341121,a0003@realestate.com,2.85,297,3.6,21,83
3,A0004,Agent A0004,+16916104878,a0004@realestate.com,1.67,31,4.5,5,61
4,A0005,Agent A0005,+18296135411,a0005@realestate.com,1.11,198,4.3,16,67

In [35]:
agents_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   agent_id          50 non-null     object
 1   name              50 non-null     object
 2   phone             50 non-null     object
 3   email             50 non-null     object
 4   commission_rate   50 non-null     float64
 5   deals_closed      50 non-null     int64
 6   rating            50 non-null     float64
 7   experience_years  50 non-null     int64
 8   avg_closing_days  50 non-null     int64
dtypes: float64(2), int64(3), object(4)
memory usage: 3.6+ KB

In [65]:
buyers_df.head(35)

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,None,0
1,2,L00866,Investor,Cheque,False,None,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,None,0
4,5,L00059,Investor,UPI,True,HDFC,4191221
5,6,L01121,End User,Cheque,True,PNB,5583760
6,7,L00324,Investor,Cheque,False,None,0
7,8,L00975,Investor,Cheque,False,None,0
8,9,L00412,Investor,Cheque,False,None,0
9,10,L00856,End User,Cash,True,Axis,4045381
10,11,L00821,End User,Cash,False,None,0
11,12,L00045,End User,Bank Transfer,False,None,0
12,13,L00050,Investor,Cheque,False,None,0
13,14,L00850,End User,UPI,True,SBI,7930296
14,15,L00241,Investor,Cheque,True,ICICI,9436023
15,16,L00171,End User,Bank Transfer,False,None,0
16,17,L00524,Investor,Cash,False,None,0
17,18,L00766,End User,Cash,False,None,0
18,19,L00839,End User,Cash,False,None,0
19,20,L00424,Investor,UPI,False,None,0
20,21,L00381,End User,Cash,True,PNB,5508034
21,22,L00610,Investor,Bank Transfer,False,None,0
22,23,L00677,End User,UPI,True,Axis,7429696
23,24,L00345,Investor,Cheque,False,None,0
24,25,L00110,Investor,Cash,True,PNB,2014020
25,26,L00278,Investor,Bank Transfer,True,Axis,6171213
26,27,L00678,Investor,Cheque,False,None,0
27,28,L00571,Investor,UPI,True,SBI,2021567
28,29,L00359,Investor,Cheque,True,Axis,4478227
29,30,L00599,End User,Bank Transfer,True,Axis,4469398
30,31,L00391,End User,Cash,True,ICICI,4951639
31,32,L00894,End User,Cash,False,None,0
32,33,L00693,Investor,UPI,False,None,0
33,34,L00728,End User,Cash,True,ICICI,1662028
34,35,L00363,End User,UPI,True,ICICI,7964815

In [52]:
buyers_df.shape

(20000, 7)

In [53]:
buyers_df =buyers_df.drop_duplicates()

In [54]:
buyers_df.isnull().sum()

buyer_id         0
sale_id          0
buyer_type       0
payment_mode     0
loan_taken       0
loan_provider    0
loan_amount      0
dtype: int64

In [55]:
buyers_df['loan_provider'] = buyers_df['loan_provider'].fillna('None')

In [41]:
buyers_df.isnull()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
19995,False,False,False,False,False,False,False
19996,False,False,False,False,False,False,False
19997,False,False,False,False,False,False,False
19998,False,False,False,False,False,False,False
19999,False,False,False,False,False,False,False

In [56]:
buyers_df.isnull().sum()

buyer_id         0
sale_id          0
buyer_type       0
payment_mode     0
loan_taken       0
loan_provider    0
loan_amount      0
dtype: int64

In [43]:
buyers_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   buyer_id       20000 non-null  int64
 1   sale_id        20000 non-null  object
 2   buyer_type     20000 non-null  object
 3   payment_mode   20000 non-null  object
 4   loan_taken     20000 non-null  bool
 5   loan_provider  20000 non-null  object
 6   loan_amount    20000 non-null  int64
dtypes: bool(1), int64(2), object(4)
memory usage: 957.2+ KB

In [44]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Listing_ID      720 non-null    object
 1   Sale_Price      720 non-null    float64
 2   Date_Sold       720 non-null    object
 3   Days_on_Market  720 non-null    float64
dtypes: float64(2), object(2)
memory usage: 22.6+ KB

In [45]:
sales_df.head()

  Listing_ID    Sale_Price   Date_Sold  Days_on_Market
0     L01179  9.255800e+05  2023-07-07       65.005560
1     L00866  1.054160e+05  2023-06-14       38.004620
2     L00102  1.825184e+06  2023-09-09       22.992622
3     L00440  1.932085e+06  2023-10-29       72.012274
4     L00059  7.765860e+05  2023-05-01      116.000152

In [46]:
sales_df.shape

(720, 4)

In [47]:
x = 2e+3 
int(x)

2000

In [48]:
sales_df['sale_price'] =sales_df['sale_price'].astype(int)

KeyError: 'sale_price'

In [ ]:
sales_df.head()

  Listing_ID  Sale_Price   Date_Sold  Days_on_Market
0     L01179      925580  2023-07-07       65.005560
1     L00866      105416  2023-06-14       38.004620
2     L00102     1825184  2023-09-09       22.992622
3     L00440     1932085  2023-10-29       72.012274
4     L00059      776585  2023-05-01      116.000152

In [ ]:
sales_df.columns = sales_df.columns.str.lower()

In [ ]:
sales_df.isnull().sum()

listing_id        0
sale_price        0
date_sold         0
days_on_market    0
dtype: int64

In [ ]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   listing_id      720 non-null    object
 1   sale_price      720 non-null    int64
 2   date_sold       720 non-null    object
 3   days_on_market  720 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 22.6+ KB

In [ ]:
sales_df["date_sold"]= pd.to_datetime(sales_df["date_sold"]).dt.date

In [ ]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 720 entries, 0 to 719
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   listing_id      720 non-null    object
 1   sale_price      720 non-null    int64
 2   date_sold       720 non-null    object
 3   days_on_market  720 non-null    float64
dtypes: float64(1), int64(1), object(2)
memory usage: 22.6+ KB

In [ ]:
sales_df.head(2)

  listing_id  sale_price   date_sold  days_on_market
0     L01179      925580  2023-07-07        65.00556
1     L00866      105416  2023-06-14        38.00462

In [ ]:
property_df.head()

,attribute_id,listing_id,bedrooms,bathrooms,floor_number,total_floors,year_built,is_rented,tenant_count,furnishing_status,metro_distance_km,parking_available,power_backup
0,1,L00001,5,3,9,9,2001,True,4,Furnished,7.26,False,True
1,2,L00002,2,2,19,29,2020,False,0,Unfurnished,4.84,True,False
2,3,L00003,2,3,8,26,2007,True,4,Semi-Furnished,4.92,False,False
3,4,L00004,3,3,25,10,2003,False,3,Furnished,1.20,False,True
4,5,L00005,2,2,15,16,2008,True,1,Semi-Furnished,7.90,False,False

In [ ]:
property_df.shape

(21200, 13)

In [ ]:
property_df =property_df.drop_duplicates()

In [ ]:
property_df.isnull().sum()

attribute_id         0
listing_id           0
bedrooms             0
bathrooms            0
floor_number         0
total_floors         0
year_built           0
is_rented            0
tenant_count         0
furnishing_status    0
metro_distance_km    0
parking_available    0
power_backup         0
dtype: int64

In [ ]:
property_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   attribute_id       21200 non-null  int64
 1   listing_id         21200 non-null  object
 2   bedrooms           21200 non-null  int64
 3   bathrooms          21200 non-null  int64
 4   floor_number       21200 non-null  int64
 5   total_floors       21200 non-null  int64
 6   year_built         21200 non-null  int64
 7   is_rented          21200 non-null  bool
 8   tenant_count       21200 non-null  int64
 9   furnishing_status  21200 non-null  object
 10  metro_distance_km  21200 non-null  float64
 11  parking_available  21200 non-null  bool
 12  power_backup       21200 non-null  bool
dtypes: bool(3), float64(1), int64(7), object(2)
memory usage: 1.7+ MB

In [ ]:
property_df.columns = property_df.columns.str.lower()

In [ ]:
# pip install mysql-connector-python

In [8]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="12345678"
    
)

print("Connected successfully!")

cur = conn.cursor()

Connected successfully!

In [11]:
cur.execute("CREATE DATABASE IF NOT EXISTS brickview")
print("Database created!")

Database created!

In [12]:
cur.execute("use brickview")

In [13]:
from sqlalchemy import create_engine
engine = create_engine("mysql+mysqlconnector://root:12345678@localhost:3306/brickview")

In [73]:
buyers_df.to_sql(name = "buyers", con= engine, if_exists= "append", index = False)

20000

In [ ]:
# import psycopg2

# # Connect to PostgreSQL (default DB)
# conn = psycopg2.connect(
#     host="localhost",
#     user="postgres",
#     password="1234",
#     dbname="postgres"
# )

# conn.autocommit = True  

# cur = conn.cursor()

# #cur.execute("CREATE DATABASE project1;")

# print("Database created successfully!")

In [ ]:
# cur.close()
# conn.close()

# conn = psycopg2.connect(
#     host="localhost",
#     user="postgres",
#     password="1234",
#     dbname="brick"
# )

# cur = conn.cursor()
# print("Connected to brick")

In [ ]:
# from sqlalchemy import create_engine, text

# # 1. Define the credentials
# USER = 'postgres'
# PASSWORD = '1234'
# HOST = 'localhost'
# PORT = '5432'


# # 2. Creation connection URL
# DATABASE_URL = f"postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}:{PORT}/postgres"


# # 3. Create the engine
# engine = create_engine(DATABASE_URL)
# print(engine)

# # 4. Connect and Execute
# try:
#     with engine.connect() as connection:
#         result = connection.execute(text("SELECT version();"))
#         print("success")
#         print(f"Postgresql version: {result.fetchone()[0]}")
# except Exception as e:
#     print("Error connecting to the database")

import psycopg2

# Connect to PostgreSQL (default DB) 
conn = psycopg2.connect(
    host="localhost",
    user="postgres",
    password="1234"
    )

conn.autocommit = True  

cur = conn.cursor()

cur.execute("CREATE DATABASE Brickview_Realestate")

# cur.execute("use Brickview_Realestate")

# print("Database created successfully!")

conn = psycopg2.connect(
    host="localhost",
    user="postgres",
    password="1234",
    dbname = "Brickview_Realestate"
    )

conn.autocommit = True  

cur = conn.cursor()

import psycopg2

conn = psycopg2.connect(
    host="localhost",
    user="postgres",
    password="1234",
    dbname="postgres"
)

conn.autocommit = True
cur = conn.cursor()

cur.execute("CREATE DATABASE Brickview_Realestate")

print("Database created!")

In [ ]:
# import psycopg2

# conn = psycopg2.connect(
#     host="localhost",
#     user="postgres",
#     password="1234",
#     dbname="postgres"
# )

# cur = conn.cursor()

# cur.execute("SELECT datname FROM pg_database;")

# for db in cur.fetchall():
#     print(db)

conn = psycopg2.connect(
    host="localhost",
    user="postgres",
    password="1234",
    dbname="Brickview_Realestate"
)

cur = conn.cursor()

print("Connected successfully!")

In [6]:
cur.execute("""CREATE TABLE IF NOT EXISTS listings(
    listing_id VARCHAR(50) PRIMARY KEY,
    city VARCHAR(50) NOT NULL,
    property_type VARCHAR(50) NOT NULL,
    price INT NOT NULL ,
    sqft NUMERIC NOT NULL ,
    date_listed DATE NOT NULL,
    agent_id VARCHAR(50) NOT NULL,
    latitude NUMERIC,
    longitude NUMERIC);
	""")
conn.commit()

In [ ]:
conn.commit()

In [ ]:
# cur.execute("""
# SELECT table_name 
# FROM information_schema.tables 
# WHERE table_schema = 'brick';
# """)

# for table in cur.fetchall():
#     print(table[0])

In [ ]:
cur.execute("""CREATE TABLE IF NOT EXISTS agents(
    agent_id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    commission_rate FLOAT NOT NULL,
    deals_closed INT  NOT NULL,
    rating FLOAT NOT NULL,
    experience_years INT  NOT NULL,
    avg_closing_days INT  NOT NULL);
	""")
conn.commit()

In [61]:
cur.execute("""CREATE TABLE IF NOT EXISTS buyers(
    buyer_id VARCHAR(50) PRIMARY KEY,
    sale_id VARCHAR(50) NOT NULL,
    buyer_type VARCHAR(50) NOT NULL,
    payment_mode VARCHAR(50) NOT NULL,
    loan_taken BOOLEAN NOT NULL,
    loan_provider VARCHAR(50) NOT NULL,
    loan_amount INT NOT NULL);
	""")
conn.commit()

In [ ]:
cur.execute("""CREATE TABLE IF NOT EXISTS sales(
    listing_id VARCHAR(50) NOT NULL,
    sale_price INT NOT NULL,
    date_sold DATE NOT NULL,
    days_on_market FLOAT NOT NULL, 
    FOREIGN KEY (listing_id) REFERENCES listings(listing_id));
	""")
conn.commit()

In [ ]:
property_df.columns

Index(['attribute_id', 'listing_id', 'bedrooms', 'bathrooms', 'floor_number',
       'total_floors', 'year_built', 'is_rented', 'tenant_count',
       'furnishing_status', 'metro_distance_km', 'parking_available',
       'power_backup'],
      dtype='object')

In [ ]:
property_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   attribute_id       21200 non-null  int64
 1   listing_id         21200 non-null  object
 2   bedrooms           21200 non-null  int64
 3   bathrooms          21200 non-null  int64
 4   floor_number       21200 non-null  int64
 5   total_floors       21200 non-null  int64
 6   year_built         21200 non-null  int64
 7   is_rented          21200 non-null  bool
 8   tenant_count       21200 non-null  int64
 9   furnishing_status  21200 non-null  object
 10  metro_distance_km  21200 non-null  float64
 11  parking_available  21200 non-null  bool
 12  power_backup       21200 non-null  bool
dtypes: bool(3), float64(1), int64(7), object(2)
memory usage: 1.7+ MB

In [ ]:
cur.execute("""CREATE TABLE IF NOT EXISTS property(
    attribute_id INT PRIMARY KEY,
    listing_id VARCHAR(50) NOT NULL,
    bedrooms INT NOT NULL,
    bathrooms INT NOT NULL,
    floor_number INT NOT NULL,
    total_floors INT NOT NULL,
    year_built   INT NOT NULL,     
    is_rented BOOLEAN NOT NULL,
    tenant_count INT NOT NULL,
    furnishing_status VARCHAR(50) NOT NULL, 
    metro_distance_km FLOAT NOT NULL, 
    parking_available BOOLEAN NOT NULL,
    power_backup BOOLEAN NOT NULL, 
    FOREIGN KEY (listing_id) REFERENCES listings(listing_id));
	""")
conn.commit()

In [ ]:
property_df.columns

Index(['attribute_id', 'listing_id', 'bedrooms', 'bathrooms', 'floor_number',
       'total_floors', 'year_built', 'is_rented', 'tenant_count',
       'furnishing_status', 'metro_distance_km', 'parking_available',
       'power_backup'],
      dtype='object')

In [ ]:
property_df.columns

Index(['attribute_id', 'listing_id', 'bedrooms', 'bathrooms', 'floor_number',
       'total_floors', 'year_built', 'is_rented', 'tenant_count',
       'furnishing_status', 'metro_distance_km', 'parking_available',
       'power_backup'],
      dtype='object')

In [ ]:
property_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21200 entries, 0 to 21199
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   attribute_id       21200 non-null  int64
 1   listing_id         21200 non-null  object
 2   bedrooms           21200 non-null  int64
 3   bathrooms          21200 non-null  int64
 4   floor_number       21200 non-null  int64
 5   total_floors       21200 non-null  int64
 6   year_built         21200 non-null  int64
 7   is_rented          21200 non-null  bool
 8   tenant_count       21200 non-null  int64
 9   furnishing_status  21200 non-null  object
 10  metro_distance_km  21200 non-null  float64
 11  parking_available  21200 non-null  bool
 12  power_backup       21200 non-null  bool
dtypes: bool(3), float64(1), int64(7), object(2)
memory usage: 1.7+ MB

In [ ]:
for i, row in listings_df.iterrows():
    cur.execute("""
    insert into listings (listing_id,city,property_type,price,sqft,date_listed,agent_id,latitude,longitude)
    values (%s,%s,%s,%s,%s,%s,%s,%s,%s)            
                 """,
    (row['listing_id'], row['city'], row['property_type'], row['price'], row['sqft'], row['date_listed'],
      row['agent_id'], row['latitude'], row['longitude']) )      
conn.commit()

In [ ]:
listings_df.columns

Index(['listing_id', 'city', 'property_type', 'price', 'sqft', 'date_listed',
       'agent_id', 'latitude', 'longitude'],
      dtype='object')

In [ ]:
agents_df.columns

Index(['agent_id', 'name', 'phone', 'email', 'commission_rate', 'deals_closed',
       'rating', 'experience_years', 'avg_closing_days'],
      dtype='object')

In [ ]:
for i, row in agents_df.iterrows():
    cur.execute("""
    insert into agents (agent_id, name, phone, email, commission_rate, deals_closed,
       rating, experience_years, avg_closing_days)
    values (%s,%s,%s,%s,%s,%s,%s,%s,%s)            
                 """,
    (row['agent_id'], row['name'], row['phone'], row['email'], row['commission_rate'], row['deals_closed'],
      row['rating'], row['experience_years'], row['avg_closing_days']) )      
conn.commit()

In [49]:
buyers_df.columns

Index(['buyer_id', 'sale_id', 'buyer_type', 'payment_mode', 'loan_taken',
       'loan_provider', 'loan_amount'],
      dtype='object')

In [50]:
buyers_df.head()

,buyer_id,sale_id,buyer_type,payment_mode,loan_taken,loan_provider,loan_amount
0,1,L01179,End User,Cash,False,None,0
1,2,L00866,Investor,Cheque,False,None,0
2,3,L00102,Investor,Cheque,True,Axis,2317757
3,4,L00440,Investor,Bank Transfer,False,None,0
4,5,L00059,Investor,UPI,True,HDFC,4191221

In [62]:
for i, row in buyers_df.iterrows():
    cur.execute("""
    insert into buyers (buyer_id, sale_id, buyer_type, payment_mode, loan_taken, loan_provider, loan_amount)
    values (%s,%s,%s,%s,%s,%s,%s)            
                 """,
    (row['buyer_id'], row['sale_id'], row['buyer_type'], row['payment_mode'], row['loan_taken'], row['loan_provider'],
      row['loan_amount']) )      
conn.commit()

In [ ]:
sales_df.columns

Index(['listing_id', 'sale_price', 'date_sold', 'days_on_market'], dtype='object')

In [ ]:
for i, row in sales_df.iterrows():
    cur.execute("""
    insert into sales (listing_id, sale_price, date_sold, days_on_market)
    values (%s,%s,%s,%s)            
                 """,
    (row['listing_id'], row['sale_price'], row['date_sold'], row['days_on_market']) )      
conn.commit()

In [ ]:
property_df.columns

Index(['attribute_id', 'listing_id', 'bedrooms', 'bathrooms', 'floor_number',
       'total_floors', 'year_built', 'is_rented', 'tenant_count',
       'furnishing_status', 'metro_distance_km', 'parking_available',
       'power_backup'],
      dtype='object')

In [ ]:
for i, row in property_df.iterrows():
    cur.execute("""
    insert into property (attribute_id, listing_id, bedrooms, bathrooms, floor_number, total_floors, year_built, is_rented, tenant_count,
                 furnishing_status, metro_distance_km, parking_available, power_backup)
    values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)            
                 """,
    (row['attribute_id'], row['listing_id'], row['bedrooms'], row['bathrooms'], row['floor_number'], row['total_floors'],
      row['year_built'], row['is_rented'], row['tenant_count'], row['furnishing_status'], row['metro_distance_km'], row['parking_available'], row['power_backup']) )      
conn.commit()

In [ ]:
agents_df.to_sql("agents", index=False)
conn.commit()

TypeError: NDFrame.to_sql() missing 1 required positional argument: 'con'

In [ ]:
 # 3. Export to PostgreSQL
 agents_df.to_sql(
    name='agents',      # Name of the SQL table #NAME OF THE  TABLE
    con=engine,               # The connection engine
    if_exists='replace',      # Options: 'fail', 'replace', or 'append'
    index=False               # Don't write the DataFrame index as a column
)

50

In [ ]:
# 3. Export to PostgreSQL
buyers_df.to_sql(
    name='brickview',      # Name of the SQL table #NAME OF THE  TABLE
    con=engine,               # The connection engine
    if_exists='replace',      # Options: 'fail', 'replace', or 'append'
    index=False               # Don't write the DataFrame index as a column
)

1000

In [ ]:
# 3. Export to PostgreSQL
sales_df.to_sql(
    name='sales',      # Name of the SQL table #NAME OF THE  TABLE
    con=engine,               # The connection engine
    if_exists='replace',      # Options: 'fail', 'replace', or 'append'
    index=False               # Don't write the DataFrame index as a column
)

720

In [ ]:
# 3. Export to PostgreSQL
property_df.to_sql(
    name='property',      # Name of the SQL table #NAME OF THE  TABLE
    con=engine,               # The connection engine
    if_exists='replace',      # Options: 'fail', 'replace', or 'append'
    index=False               # Don't write the DataFrame index as a column
)

200

# QUESTIONS

### 1. What is the average listing price by city?

In [ ]:
query = "SELECT city, (ROUND(AVG(price),2)) FROM listings GROUP BY city;" 
cur.execute(query)

rows = cur.fetchall()

for row in rows:
    print(row)

('New York', Decimal('2493319.24'))
('Los Angeles', Decimal('2442417.83'))
('Houston', Decimal('2436810.51'))
('Phoenix', Decimal('2459961.26'))
('Chicago', Decimal('2430677.42'))

### 1. What is the average listing price by city?

In [7]:
query = "SELECT city, (ROUND(AVG(price),2)) FROM listings GROUP BY city;" 
df1 = pd.read_sql(query, conn) 
df1

C:\Users\user\AppData\Local\Temp\ipykernel_10272\825409390.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df1 = pd.read_sql(query, conn)

          city  (ROUND(AVG(price),2))
0     New York             2493319.24
1  Los Angeles             2442417.83
2      Houston             2436810.51
3      Phoenix             2459961.26
4      Chicago             2430677.42

### 2. What is the average price per square foot by property type?

In [8]:
query = "SELECT property_type, AVG(price/sqft) AS avg_price_per_sqft FROM listings GROUP BY property_type;" 
df2 = pd.read_sql(query, conn) 
df2

C:\Users\user\AppData\Local\Temp\ipykernel_10272\1901416904.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql(query, conn)

  property_type  avg_price_per_sqft
0     Apartment          792.192911
1     Townhouse          789.745657
2         House          796.040335
3         Condo          754.679897

### 3. How does furnishing status impact property prices?

In [ ]:
query = """select p.furnishing_status, (ROUND(AVG(l.price),2)) as avg_price
         from listings l join property p ON l.listing_id = p.listing_id  
         GROUP BY 1;"""
df3 = pd.read_sql(query, conn) 
df3

C:\Users\user\AppData\Local\Temp\ipykernel_26008\1480336461.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df3 = pd.read_sql(query, conn)

  furnishing_status   avg_price
0         Furnished  2463538.57
1       Unfurnished  2433974.61
2    Semi-Furnished  2461192.15

###  4. Do properties closer to metro stations command higher prices?

In [ ]:
query = """select p.metro_distance_km, (ROUND(AVG(l.price),2)) as avg_price
           from listings l join property p ON l.listing_id = p.listing_id  
           GROUP BY 1
           ORDER BY 2 DESC;"""
df4= pd.read_sql(query, conn) 
df4

### 5. Are rented properties priced differently from non-rented ones?

In [ ]:
query = """select p.is_rented, (ROUND(AVG(l.price),2)) as avg_price
           from listings l join property p ON l.listing_id = p.listing_id  
           GROUP BY 1
           ORDER BY 2 DESC;"""
df5= pd.read_sql(query, conn) 
df5

C:\Users\user\AppData\Local\Temp\ipykernel_26008\956457820.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df5= pd.read_sql(query, conn)

   is_rented   avg_price
0          1  2457184.41
1          0  2448249.81

###  6. How do bedrooms and bathrooms affect pricing?

In [ ]:
query = """select bedrooms, bathrooms, (ROUND(AVG(l.price),2)) as avg_price
           from listings l join property p ON l.listing_id = p.listing_id  
           GROUP BY 1,2
           Order by 3;"""
df6= pd.read_sql(query, conn) 
df6

C:\Users\user\AppData\Local\Temp\ipykernel_26008\4151161551.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df6= pd.read_sql(query, conn)

    bedrooms  bathrooms   avg_price
0          2          2  2378687.17
1          5          1  2384939.97
2          4          3  2393514.53
3          3          2  2409122.23
4          5          3  2424066.33
5          3          1  2426007.47
6          1          1  2434000.94
7          4          1  2434955.89
8          4          2  2450749.50
9          3          3  2455023.77
10         1          4  2455532.47
11         2          1  2455734.86
12         1          3  2459032.09
13         4          4  2471535.40
14         5          2  2478067.68
15         3          4  2478880.73
16         2          3  2482618.44
17         1          2  2509474.29
18         5          4  2527191.48
19         2          4  2555765.73

### 7. Do properties with parking and power backup sell at higher prices?

In [ ]:
query = """select parking_available, power_backup, (ROUND(AVG(l.price),2)) as avg_price
          from listings l join property p ON l.listing_id = p.listing_id  
          GROUP BY 1,2
          Order by 3;"""
df7= pd.read_sql(query, conn) 
df7

C:\Users\user\AppData\Local\Temp\ipykernel_26008\3584715710.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df7= pd.read_sql(query, conn)

   parking_available  power_backup   avg_price
0                  0             0  2436677.26
1                  0             1  2446292.09
2                  1             0  2462363.31
3                  1             1  2465651.13

### 8. How does year built influence listing price?

In [ ]:
query = """select p.year_built, (ROUND(AVG(l.price),2)) as avg_price
           from listings l join property p ON l.listing_id = p.listing_id  
           GROUP BY 1
           ORDER BY 2 DESC;"""
df8= pd.read_sql(query, conn) 
df8

### 9. Which cities have the highest median property prices?

In [9]:
query = """SELECT city, ROUND(AVG(price),2) AS avg_price FROM listings
GROUP BY CITY 
ORDER BY 2 DESC;"""
df9= pd.read_sql(query, conn) 
df9

C:\Users\user\AppData\Local\Temp\ipykernel_10368\4290724646.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df9= pd.read_sql(query, conn)

          city   avg_price
0     New York  2493319.24
1      Phoenix  2459961.26
2  Los Angeles  2442417.83
3      Houston  2436810.51
4      Chicago  2430677.42

### 10. How are properties distributed across price buckets?

In [10]:
query = """SELECT 
    CASE 
        WHEN price < 100000 THEN 'Below 10Lakhs'
        WHEN price BETWEEN 100000 AND 300000 THEN '10 - 30Lakhs'
        WHEN price BETWEEN 300000 AND 500000 THEN '30 - 50Lakhs'
        WHEN price BETWEEN 500000 AND 1000000 THEN '50Lakhs - 1Crore'
        ELSE 'Above 1Crore'
    END AS price_bucket,
    
    COUNT(*) AS property_count

FROM listings
GROUP BY price_bucket
ORDER BY property_count DESC;"""
df10= pd.read_sql(query, conn) 
df10

C:\Users\user\AppData\Local\Temp\ipykernel_10368\852227205.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df10= pd.read_sql(query, conn)

       price_bucket  property_count
0      Above 1Crore           16931
1  50Lakhs - 1Crore            2402
2      30 - 50Lakhs             945
3      10 - 30Lakhs             922

###  Sales & Market Performance

### 11. What is the average days on market by city?

In [ ]:
query = """SELECT l.city, CEIL(AVG(s.days_on_market)) AS avg_days_on_market
           FROM listings l JOIN sales s
           ON l.listing_id = s.listing_id
           GROUP BY 1;"""
df11 = pd.read_sql(query, conn) 
df11

C:\Users\user\AppData\Local\Temp\ipykernel_26008\1072353531.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df11 = pd.read_sql(query, conn)

          city  avg_days_on_market
0      Phoenix                60.0
1      Houston                59.0
2      Chicago                65.0
3  Los Angeles                66.0
4     New York                61.0

### 12. Which property types sell the fastest?

In [ ]:
query = """SELECT l.property_type , CEIL(AVG(s.date_sold - l.date_listed)) AS no_of_days
           FROM listings l join sales s
           ON l.listing_id = s.listing_id
           GROUP BY 1
           ORDER BY 2 ASC;"""
df12 = pd.read_sql(query, conn) 
df12

C:\Users\user\AppData\Local\Temp\ipykernel_26008\3416531707.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df12 = pd.read_sql(query, conn)

  property_type  no_of_days
0     Townhouse        1097
1         House        1166
2         Condo        1300
3     Apartment        1349

### 13. What percentage of properties are sold above listing price?

In [12]:
query = """SELECT 
    ROUND(
        (COUNT(*) * 100.0) / 
        (SELECT COUNT(*) 
         FROM listings l 
         JOIN sales s 
         ON l.listing_id = s.listing_id),2) AS percentage_above_listing
FROM listings l JOIN sales s 
ON l.listing_id = s.listing_id
WHERE s.sale_price > l.price; """
df13 = pd.read_sql(query, conn) 
df13

C:\Users\user\AppData\Local\Temp\ipykernel_10368\1495252086.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df13 = pd.read_sql(query, conn)

   percentage_above_listing
0                     49.31

###  14. What is the sale-to-list price ratio by city?

In [ ]:
query = """SELECT l.city, ROUND(AVG(s.sale_price / l.price),2) AS sale_to_list_price_ratio
           FROM listings l JOIN sales s
           ON l.listing_id = s.listing_id
           GROUP BY 1;"""
df14 = pd.read_sql(query, conn) 
df14

C:\Users\user\AppData\Local\Temp\ipykernel_26008\808750866.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df14 = pd.read_sql(query, conn)

          city  sale_to_list_price_ratio
0      Phoenix                       1.0
1      Houston                       1.0
2      Chicago                       1.0
3  Los Angeles                       1.0
4     New York                       1.0

### 15. Which listings took more than 90 days to sell?

In [ ]:
query = """SELECT l.listing_id , CEIL(s.date_sold - l.date_listed) AS no_of_days
           from listings l join sales s
           ON l.listing_id = s.listing_id
           WHERE CEIL(s.date_sold - l.date_listed) > 90
           ORDER BY 2 ASC;"""
df15 = pd.read_sql(query, conn) 
df15

C:\Users\user\AppData\Local\Temp\ipykernel_26008\3836787093.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df15 = pd.read_sql(query, conn)

    listing_id  no_of_days
0       L00948          91
1       L01056          91
2       L00499          91
3       L00102          92
4       L00436          92
..         ...         ...
586     L00057        9197
587     L00271        9197
588     L00862        9197
589     L00287        9198
590     L00351        9198

[591 rows x 2 columns]

### 16. How does metro distance affect time on market?

In [ ]:
query = """SELECT p.metro_distance_km, CEIL(AVG(s.days_on_market)) AS days_on_market
FROM property p JOIN sales s
ON p.listing_id = s.listing_id
GROUP BY 1
ORDER BY 2 ASC;"""
df16 = pd.read_sql(query, conn) 
df16

C:\Users\user\AppData\Local\Temp\ipykernel_26008\1202706507.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df16 = pd.read_sql(query, conn)

     metro_distance_km  days_on_market
0                 3.11             5.0
1                 3.32             6.0
2                 0.46             6.0
3                 0.63             6.0
4                 5.21             7.0
..                 ...             ...
458               1.37           119.0
459               4.45           119.0
460               7.27           120.0
461               5.65           120.0
462               2.64           121.0

[463 rows x 2 columns]

### 17. What is the monthly sales trend?

In [13]:
query = """SELECT 
    EXTRACT(YEAR FROM date_sold) AS year,
    EXTRACT(MONTH FROM date_sold) AS month,
    COUNT(*) AS total_sales
FROM sales 
GROUP BY year, month
ORDER BY year, month;"""
df17 = pd.read_sql(query, conn) 
df17

C:\Users\user\AppData\Local\Temp\ipykernel_10368\3686576190.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df17 = pd.read_sql(query, conn)

    year  month  total_sales
0   2023      1            7
1   2023      2           17
2   2023      3           20
3   2023      4           36
4   2023      5           45
5   2023      6           31
6   2023      7           48
7   2023      8           50
8   2023      9           46
9   2023     10           64
10  2023     11           46
11  2023     12           42
12  2024      1           44
13  2024      2           44
14  2024      3           39
15  2024      4           29
16  2024      5           45
17  2024      6           29
18  2024      7           24
19  2024      8           13
20  2024      9            1

### 18. Which properties are currently unsold?

In [14]:
query = """SELECT l.listing_id
FROM listings l LEFT JOIN sales s 
ON l.listing_id = s.listing_id 
WHERE s.date_sold IS NULL
;"""
df18 = pd.read_sql(query, conn) 
df18

C:\Users\user\AppData\Local\Temp\ipykernel_10368\378662640.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df18 = pd.read_sql(query, conn)

      listing_id
0         L00002
1         L00005
2         L00009
3         L00014
4         L00015
...          ...
20475     L21196
20476     L21197
20477     L21198
20478     L21199
20479     L21200

[20480 rows x 1 columns]

### Agent Performance

### 19.Which agents have closed the most sales?

In [ ]:
query = """SELECT agent_id, name, deals_closed FROM agents
           ORDER BY 3 DESC 
           LIMIT 5;"""
df19 = pd.read_sql(query, conn) 
df19

C:\Users\user\AppData\Local\Temp\ipykernel_26008\4141413406.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df19 = pd.read_sql(query, conn)

  agent_id         name  deals_closed
0    A0003  Agent A0003           297
1    A0030  Agent A0030           296
2    A0010  Agent A0010           292
3    A0024  Agent A0024           283
4    A0011  Agent A0011           270

### 20.Who are the top agents by total sales revenue?

In [15]:
query = """SELECT 
    a.agent_id,
    a.name,
    SUM(s.sale_price) AS total_revenue
FROM agents a
JOIN listings l 
    ON a.agent_id = l.agent_id
JOIN sales s 
    ON l.listing_id = s.listing_id
GROUP BY a.agent_id, a.name
ORDER BY total_revenue DESC;"""
df20 = pd.read_sql(query, conn) 
df20

C:\Users\user\AppData\Local\Temp\ipykernel_10368\2324089763.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df20 = pd.read_sql(query, conn)

   agent_id         name  total_revenue
0     A0011  Agent A0011     27882260.0
1     A0042  Agent A0042     27191594.0
2     A0043  Agent A0043     24102410.0
3     A0035  Agent A0035     22725744.0
4     A0014  Agent A0014     22034000.0
5     A0046  Agent A0046     21335793.0
6     A0048  Agent A0048     21186298.0
7     A0027  Agent A0027     21099687.0
8     A0009  Agent A0009     20279266.0
9     A0029  Agent A0029     19586489.0
10    A0039  Agent A0039     19223004.0
11    A0036  Agent A0036     19209536.0
12    A0050  Agent A0050     18968538.0
13    A0025  Agent A0025     18818583.0
14    A0017  Agent A0017     18583845.0
15    A0007  Agent A0007     18414468.0
16    A0001  Agent A0001     18173913.0
17    A0015  Agent A0015     17752850.0
18    A0019  Agent A0019     16730603.0
19    A0021  Agent A0021     16548301.0
20    A0006  Agent A0006     16523224.0
21    A0031  Agent A0031     15723285.0
22    A0003  Agent A0003     15584944.0
23    A0018  Agent A0018     15539870.0
24    A0012  Agent A0012     14730528.0
25    A0023  Agent A0023     14634864.0
26    A0010  Agent A0010     14228157.0
27    A0033  Agent A0033     14202137.0
28    A0041  Agent A0041     14077476.0
29    A0049  Agent A0049     13954940.0
30    A0047  Agent A0047     13478174.0
31    A0016  Agent A0016     13450347.0
32    A0024  Agent A0024     13196013.0
33    A0004  Agent A0004     12754762.0
34    A0030  Agent A0030     12484439.0
35    A0037  Agent A0037     12314983.0
36    A0040  Agent A0040     12039284.0
37    A0045  Agent A0045     11819068.0
38    A0002  Agent A0002     11754960.0
39    A0008  Agent A0008     11071893.0
40    A0038  Agent A0038     11060632.0
41    A0032  Agent A0032     10653313.0
42    A0044  Agent A0044     10247545.0
43    A0005  Agent A0005     10114383.0
44    A0028  Agent A0028      9831887.0
45    A0020  Agent A0020      9605498.0
46    A0013  Agent A0013      9114415.0
47    A0026  Agent A0026      8479512.0
48    A0034  Agent A0034      7011392.0
49    A0022  Agent A0022      6303597.0

### 21.Which agents close deals fastest?

In [ ]:
query = """SELECT agent_id, name, avg_closing_days FROM agents
           ORDER BY 3 ASC;"""
df21 = pd.read_sql(query, conn) 
df21

### 22.Does experience correlate with deals closed?

In [ ]:
query = """SELECT deals_closed, experience_years FROM agents
           ORDER BY 2 DESC;"""
df22 = pd.read_sql(query, conn) 
df22

### 23.Do agents with higher ratings close deals faster?

In [ ]:
query = """SELECT rating, avg_closing_days FROM agents
           ORDER BY 1 DESC;"""
df23 = pd.read_sql(query, conn) 
df23

C:\Users\user\AppData\Local\Temp\ipykernel_26008\1646387215.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df23 = pd.read_sql(query, conn)

    rating  avg_closing_days
0      5.0                42
1      5.0                65
2      4.9                49
3      4.9                60
4      4.8                65
5      4.8                56
6      4.8                52
7      4.8                31
8      4.6                36
9      4.5                61
10     4.4                38
11     4.3                58
12     4.3                21
13     4.3                67
14     4.3                64
15     4.3                84
16     4.2                26
17     4.1                84
18     4.1                39
19     4.1                79
20     4.1                23
21     4.1                77
22     4.1                33
23     4.0                33
24     4.0                33
25     4.0                15
26     3.8                82
27     3.8                68
28     3.7                69
29     3.7                85
30     3.6                83
31     3.6                35
32     3.6                77
33     3.6                27
34     3.6                60
35     3.5                82
36     3.5                68
37     3.5                76
38     3.4                20
39     3.4                90
40     3.4                72
41     3.3                77
42     3.3                33
43     3.2                44
44     3.2                89
45     3.2                58
46     3.2                48
47     3.1                62
48     3.1                57
49     3.1                31

### 24.What is the average commission earned by each agent?

In [ ]:
query = """SELECT agent_id, commission_rate AS avg_commission FROM agents;"""
df24 = pd.read_sql(query, conn) 
df24

C:\Users\user\AppData\Local\Temp\ipykernel_26008\2775077492.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df24 = pd.read_sql(query, conn)

   agent_id  avg_commission
0     A0001            2.00
1     A0002            2.20
2     A0003            2.85
3     A0004            1.67
4     A0005            1.11
5     A0006            1.58
6     A0007            1.78
7     A0008            1.72
8     A0009            2.85
9     A0010            2.14
10    A0011            2.01
11    A0012            2.37
12    A0013            1.78
13    A0014            1.97
14    A0015            1.49
15    A0016            1.45
16    A0017            2.14
17    A0018            2.63
18    A0019            2.80
19    A0020            2.67
20    A0021            2.73
21    A0022            1.94
22    A0023            1.89
23    A0024            2.95
24    A0025            2.01
25    A0026            1.63
26    A0027            1.92
27    A0028            2.25
28    A0029            2.45
29    A0030            2.79
30    A0031            2.51
31    A0032            2.57
32    A0033            2.56
33    A0034            2.46
34    A0035            2.96
35    A0036            1.73
36    A0037            1.78
37    A0038            1.22
38    A0039            1.37
39    A0040            1.58
40    A0041            1.32
41    A0042            2.24
42    A0043            1.75
43    A0044            1.45
44    A0045            2.50
45    A0046            1.57
46    A0047            1.63
47    A0048            1.34
48    A0049            1.70
49    A0050            2.56

### 25.Which agents currently have the most active listings?--------------------------UNSOLD(ACTIVE-STILL IN THE MARKET)

In [16]:
query = """SELECT 
           l.agent_id, COUNT(*) AS active_listings
           FROM listings l LEFT JOIN sales s 
           ON l.listing_id = s.listing_id
WHERE s.listing_id IS NULL
GROUP BY l.agent_id
ORDER BY active_listings DESC;"""
df25 = pd.read_sql(query, conn) 
df25

C:\Users\user\AppData\Local\Temp\ipykernel_10368\2070780532.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df25 = pd.read_sql(query, conn)

   agent_id  active_listings
0     A0023              446
1     A0011              439
2     A0008              438
3     A0042              435
4     A0014              432
5     A0044              430
6     A0020              426
7     A0048              425
8     A0012              425
9     A0015              425
10    A0016              424
11    A0018              422
12    A0036              422
13    A0031              422
14    A0033              418
15    A0022              417
16    A0040              416
17    A0027              415
18    A0010              415
19    A0002              414
20    A0037              413
21    A0026              412
22    A0005              412
23    A0007              411
24    A0045              410
25    A0035              410
26    A0021              409
27    A0009              409
28    A0050              409
29    A0043              408
30    A0028              407
31    A0004              406
32    A0032              404
33    A0047              404
34    A0006              403
35    A0038              401
36    A0041              399
37    A0046              397
38    A0030              396
39    A0029              395
40    A0013              395
41    A0001              392
42    A0034              388
43    A0017              388
44    A0049              387
45    A0019              386
46    A0025              384
47    A0039              380
48    A0024              380
49    A0003              379

### Buyer & Financing Behavior

### 26. What percentage of buyers are investors vs end users?

In [19]:
query = """SELECT 
                 ROUND((COUNT(CASE WHEN buyer_type = 'Investor' THEN 1 END) * 100.0) / COUNT(*), 2) AS perc_investors,
                 ROUND((COUNT(CASE WHEN buyer_type = 'End User' THEN 1 END) * 100.0) / COUNT(*), 2) AS perc_enduser
                 FROM buyers;"""
df26 = pd.read_sql(query, conn) 
df26

C:\Users\user\AppData\Local\Temp\ipykernel_10368\2134130547.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df26 = pd.read_sql(query, conn)

   perc_investors  perc_enduser
0            49.9          50.1

### 27. Which cities have the highest loan uptake rate?

In [21]:
query = """SELECT l.city,
       COUNT(CASE WHEN b.loan_taken = TRUE THEN 1 END) AS total_loans,
       ROUND(
           100.0 * SUM(CASE WHEN b.loan_taken = TRUE THEN 1 ELSE 0 END) / COUNT(*),
           2
       ) AS loan_uptake_rate
FROM buyers b
JOIN sales s
ON b.sale_id = s.listing_id
JOIN listings l
ON s.listing_id = l.listing_id
GROUP BY l.city
ORDER BY loan_uptake_rate DESC;"""
df27 = pd.read_sql(query, conn) 
df27

C:\Users\user\AppData\Local\Temp\ipykernel_10368\1813723414.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df27 = pd.read_sql(query, conn)

          city  total_loans  loan_uptake_rate
0  Los Angeles         1811             50.99
1      Chicago         2188             50.57
2     New York         1913             50.22
3      Houston         1809             49.71
4      Phoenix         2313             49.50

### 28. What is the average loan amount by buyer type?

In [18]:
query = """SELECT buyer_type, AVG(loan_amount) AS avg_loan_amt 
           FROM buyers
           WHERE loan_taken = 1
           GROUP BY 1;"""
df28= pd.read_sql(query, conn) 
df28["avg_loan_amt"] = df28["avg_loan_amt"].astype(int) 
df28

C:\Users\user\AppData\Local\Temp\ipykernel_6468\391631925.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df28= pd.read_sql(query, conn)

  buyer_type  avg_loan_amt
0   Investor       5211545
1   End User       5210307

### 29. Which payment mode is most commonly used?

In [26]:
query = """SELECT payment_mode, COUNT(payment_mode) FROM buyers
GROUP BY 1 
ORDER BY 2 DESC
LIMIT 1;"""
df29= pd.read_sql(query, conn) 
df29

C:\Users\user\AppData\Local\Temp\ipykernel_10368\2323347668.py:5: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df29= pd.read_sql(query, conn)

  payment_mode  COUNT(payment_mode)
0         Cash                 5088

### 30. Do loan-backed purchases take longer to close

In [ ]:
query = """SELECT 
    b.loan_taken,
    ROUND(AVG(DATEDIFF(s.date_sold, l.date_listed)), 2) AS avg_days_to_close
FROM buyers b
JOIN sales s 
    ON b.sale_id = s.listing_id
JOIN listings l 
    ON s.listing_id = l.listing_id
GROUP BY b.loan_taken;"""
df30= pd.read_sql(query, conn) 
df30

C:\Users\user\AppData\Local\Temp\ipykernel_10368\179311124.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df29= pd.read_sql(query, conn)

   loan_taken  avg_days_to_close
0           0              61.07
1           1              62.15